services:
  - type: web
    name: AppDipendenti
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: Gestionale
      - key: JWT_SECRET
        sync: false
      - key: PIN_CODE
        value: "141574"
      - key: ANTHROPIC_API_KEY
        sync: false
